name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Publish .NET Core Project
      run: dotnet publish GitHubPages.csproj -c Release -o release --nologo
      working-directory: GitHubPages

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: GitHubPages/bin/Release/net9.0/publish/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: gethub-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
        
    #- name: Commit wwwroot to GitHub Pages
    #  uses: JamesIves/github-pages-deploy-action@3.7.1
    #  with:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    BRANCH: gh-pages
    #    FOLDER: release/wwwroot
