name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ dev ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Publish .NET Core Project
      run: dotnet publish GitHubPages.csproj -c Release -o release --nologo
      working-directory: GitHubPages

    #- name: Commit wwwroot to GitHub Pages
    #  uses: JamesIves/github-pages-deploy-action@3.7.1
    #  with:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    BRANCH: gh-pages
    #    FOLDER: release/wwwroot
